# Form implementation generated from reading ui file '密码生成器.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PasswordGenerate(object):
    def setupUi(self, PasswordGenerate):
        PasswordGenerate.setObjectName("PasswordGenerate")
        PasswordGenerate.resize(292, 253)
        self.centralwidget = QtWidgets.QWidget(parent=PasswordGenerate)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_newPwd = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_newPwd.setFont(font)
        self.btn_newPwd.setObjectName("btn_newPwd")
        self.verticalLayout.addWidget(self.btn_newPwd)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        PasswordGenerate.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=PasswordGenerate)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 292, 24))
        self.menubar.setObjectName("menubar")
        PasswordGenerate.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=PasswordGenerate)
        self.statusbar.setObjectName("statusbar")
        PasswordGenerate.setStatusBar(self.statusbar)

        self.retranslateUi(PasswordGenerate)
        QtCore.QMetaObject.connectSlotsByName(PasswordGenerate)

    def retranslateUi(self, PasswordGenerate):
        _translate = QtCore.QCoreApplication.translate
        PasswordGenerate.setWindowTitle(_translate("PasswordGenerate", "密码生成器"))
        self.btn_newPwd.setText(_translate("PasswordGenerate", "生成新的密码"))
